'use client'

import { useState } from 'react'

export function ExportPdfButton() {
  const [loading, setLoading] = useState(false)

  const handleExport = async () => {
    setLoading(true)
    try {
      const html2pdf = (await import('html2pdf.js')).default

      const element = document.createElement('div')
      element.innerHTML = `
        <div style="padding: 40px; font-family: sans-serif; color: #1a1a1a;">
          <h1 style="color: #2F855A; text-align: center; border-bottom: 2px solid #2F855A; padding-bottom: 10px;">NutriSoy by Altaf - Progress Report</h1>
          <div style="margin-top: 30px;">
            <h2>Data Profil</h2>
            <p><strong>Nama:</strong> ${document.querySelector('input[placeholder="Nama kamu"]')?.getAttribute('value') || '-'}</p>
            <p><strong>Berat / Tinggi:</strong> ${document.querySelectorAll('input[type="number"]')[0]?.getAttribute('value') || '-'} kg / ${document.querySelectorAll('input[type="number"]')[1]?.getAttribute('value') || '-'} cm</p>
            <p><strong>Tujuan:</strong> ${document.querySelector('select')?.value || '-'}</p>
          </div>
          <div style="margin-top: 30px; background: #f0fdf4; padding: 20px; border-radius: 12px;">
            <h3 style="color: #22543d; margin-top: 0;">Jadwal Konsumsi Disarankan</h3>
            <ul style="line-height: 1.8;">
              <li>🌅 07:00 - Sarapan + NutriSoy #1 (25g)</li>
              <li>🥤 10:00 - NutriSoy #2 (25g) — mid-morning</li>
              <li>🥗 13:00 - Makan Siang Sehat</li>
              <li>💪 18:30 - NutriSoy #3 post-workout (25g)</li>
              <li>😴 22:00 - NutriSoy sebelum tidur (opsional)</li>
            </ul>
          </div>
          <div style="margin-top: 40px; text-align: center; font-size: 12px; color: #666;">
            <p>Generated by AI Coach NutriSoy</p>
            <p>Pemesanan via WA: 085293306853 (Altaf)</p>
          </div>
        </div>
      `

      const opt = {
        margin: 1,
        filename: 'NutriSoy-Report.pdf',
        image: { type: 'jpeg' as const, quality: 0.98 },
        html2canvas: { scale: 2 },
        jsPDF: { unit: 'in', format: 'letter', orientation: 'portrait' as const }
      }

      await html2pdf().set(opt).from(element).save()
    } catch (e) {
      console.error(e)
      alert("Gagal membuat PDF.")
    } finally {
      setLoading(false)
    }
  }

  return (
    <button 
      onClick={handleExport}
      disabled={loading}
      className="btn-secondary !w-auto flex items-center justify-center gap-2"
    >
      <span className="text-xl">📄</span>
      {loading ? 'Menyiapkan PDF...' : 'Download PDF Progress'}
    </button>
  )
}
